"""Trouble Brewing (暗流涌动) 22 character role definitions."""
from __future__ import annotations

from src.engine.types import CharacterType, RoleId
from src.roles.base import RoleDefinition

ROLES: dict[RoleId, RoleDefinition] = {
    # ------------------ TOWNSFOLK (13) ------------------
    RoleId.WASHERWOMAN: RoleDefinition(
        id=RoleId.WASHERWOMAN,
        type=CharacterType.TOWNSFOLK,
        name_zh="洗衣妇",
        name_en="Washerwoman",
        description_zh="首夜，你会得知两名玩家中的一人是特定的镇民。",
        first_night_order=3,
        other_night_order=None,
        is_info_role=True,
    ),
    RoleId.LIBRARIAN: RoleDefinition(
        id=RoleId.LIBRARIAN,
        type=CharacterType.TOWNSFOLK,
        name_zh="图书管理员",
        name_en="Librarian",
        description_zh="首夜，你会得知两名玩家中的一人是特定的外来者（或者没有外来者在场）。",
        first_night_order=4,
        other_night_order=None,
        is_info_role=True,
    ),
    RoleId.INVESTIGATOR: RoleDefinition(
        id=RoleId.INVESTIGATOR,
        type=CharacterType.TOWNSFOLK,
        name_zh="调查员",
        name_en="Investigator",
        description_zh="首夜，你会得知两名玩家中的一人是特定的爪牙。",
        first_night_order=5,
        other_night_order=None,
        is_info_role=True,
    ),
    RoleId.CHEF: RoleDefinition(
        id=RoleId.CHEF,
        type=CharacterType.TOWNSFOLK,
        name_zh="厨师",
        name_en="Chef",
        description_zh="首夜，你会得知有多少对相邻的邪恶玩家。",
        first_night_order=6,
        other_night_order=None,
        is_info_role=True,
    ),
    RoleId.EMPATH: RoleDefinition(
        id=RoleId.EMPATH,
        type=CharacterType.TOWNSFOLK,
        name_zh="共情者",
        name_en="Empath",
        description_zh="每晚，你会得知与你相邻的存活玩家中有多少名邪恶玩家。",
        first_night_order=7,
        other_night_order=8,
        is_info_role=True,
        is_ongoing_info=True,
    ),
    RoleId.FORTUNE_TELLER: RoleDefinition(
        id=RoleId.FORTUNE_TELLER,
        type=CharacterType.TOWNSFOLK,
        name_zh="占卜师",
        name_en="Fortune Teller",
        description_zh="每晚，选择两名玩家：你会得知他们之中是否有恶魔。有一名善良玩家会被你当成恶魔（红鲱鱼）。",
        first_night_order=8,
        other_night_order=9,
        is_info_role=True,
        is_ongoing_info=True,
    ),
    RoleId.UNDERTAKER: RoleDefinition(
        id=RoleId.UNDERTAKER,
        type=CharacterType.TOWNSFOLK,
        name_zh="送葬者",
        name_en="Undertaker",
        description_zh="每晚（除首夜外），你会得知今天白天死于处决的玩家的角色。",
        first_night_order=None,
        other_night_order=7,
        is_info_role=True,
        is_ongoing_info=True,
    ),
    RoleId.MONK: RoleDefinition(
        id=RoleId.MONK,
        type=CharacterType.TOWNSFOLK,
        name_zh="僧侣",
        name_en="Monk",
        description_zh="每晚（除首夜外），选择除你以外的一名玩家：今晚他免受恶魔能力的侵害。",
        first_night_order=None,
        other_night_order=2,
        is_protection_role=True,
    ),
    RoleId.RAVENKEEPER: RoleDefinition(
        id=RoleId.RAVENKEEPER,
        type=CharacterType.TOWNSFOLK,
        name_zh="守鸦人",
        name_en="Ravenkeeper",
        description_zh="如果你在夜间死亡，你会醒来并选择一名玩家：你会得知他的真实角色。",
        first_night_order=None,
        other_night_order=6,
        is_info_role=True,
    ),
    RoleId.VIRGIN: RoleDefinition(
        id=RoleId.VIRGIN,
        type=CharacterType.TOWNSFOLK,
        name_zh="贞洁者",
        name_en="Virgin",
        description_zh="当你第一次被提名时，如果提名者是镇民，该提名者立即被处决，白天直接结束。",
        first_night_order=None,
        other_night_order=None,
        is_once_per_game=True,
    ),
    RoleId.SLAYER: RoleDefinition(
        id=RoleId.SLAYER,
        type=CharacterType.TOWNSFOLK,
        name_zh="猎手",
        name_en="Slayer",
        description_zh="每个白天一次，你可以公开选择一名玩家：如果他是恶魔，他死亡。",
        first_night_order=None,
        other_night_order=None,
        is_once_per_game=True,
    ),
    RoleId.SOLDIER: RoleDefinition(
        id=RoleId.SOLDIER,
        type=CharacterType.TOWNSFOLK,
        name_zh="士兵",
        name_en="Soldier",
        description_zh="你免受恶魔能力的侵害。",
        first_night_order=None,
        other_night_order=None,
        is_protection_role=True,
    ),
    RoleId.MAYOR: RoleDefinition(
        id=RoleId.MAYOR,
        type=CharacterType.TOWNSFOLK,
        name_zh="镇长",
        name_en="Mayor",
        description_zh="如果只有三名玩家存活且白天没有人被处决，你的阵营获胜。如果你在夜间即将死亡，可能会有另一名玩家代替你死亡。",
        first_night_order=None,
        other_night_order=None,
    ),

    # ------------------ OUTSIDERS (4) ------------------
    RoleId.BUTLER: RoleDefinition(
        id=RoleId.BUTLER,
        type=CharacterType.OUTSIDER,
        name_zh="管家",
        name_en="Butler",
        description_zh="每晚，选择除你以外的一名玩家作为主人。白天只有在主人举手投票时，你才能举手投票。",
        first_night_order=9,
        other_night_order=10,
    ),
    RoleId.DRUNK: RoleDefinition(
        id=RoleId.DRUNK,
        type=CharacterType.OUTSIDER,
        name_zh="酒鬼",
        name_en="Drunk",
        description_zh="你以为自己是一个镇民，但你其实不是，且你没有该镇民的能力。",
        first_night_order=None,
        other_night_order=None,
    ),
    RoleId.RECLUSE: RoleDefinition(
        id=RoleId.RECLUSE,
        type=CharacterType.OUTSIDER,
        name_zh="陌客",
        name_en="Recluse",
        description_zh="你可能会被查验登记为邪恶、爪牙或恶魔，即使你已经死亡。",
        first_night_order=None,
        other_night_order=None,
    ),
    RoleId.SAINT: RoleDefinition(
        id=RoleId.SAINT,
        type=CharacterType.OUTSIDER,
        name_zh="圣徒",
        name_en="Saint",
        description_zh="如果你死于处决，你的阵营失败（邪恶阵营获胜）。",
        first_night_order=None,
        other_night_order=None,
    ),

    # ------------------ MINIONS (4) ------------------
    RoleId.POISONER: RoleDefinition(
        id=RoleId.POISONER,
        type=CharacterType.MINION,
        name_zh="投毒者",
        name_en="Poisoner",
        description_zh="每晚，选择一名玩家：他在今晚和明天白天处于中毒状态。",
        first_night_order=1,
        other_night_order=1,
    ),
    RoleId.SPY: RoleDefinition(
        id=RoleId.SPY,
        type=CharacterType.MINION,
        name_zh="间谍",
        name_en="Spy",
        description_zh="每晚，你可以查看魔典。你可能会被查验登记为善良、镇民或外来者，即使你已经死亡。",
        first_night_order=2,
        other_night_order=3,
        is_info_role=True,
    ),
    RoleId.SCARLET_WOMAN: RoleDefinition(
        id=RoleId.SCARLET_WOMAN,
        type=CharacterType.MINION,
        name_zh="红唇女郎",
        name_en="Scarlet Woman",
        description_zh="当恶魔死亡时，若存活玩家人数不少于五人，你成为恶魔。",
        first_night_order=None,
        other_night_order=4,
    ),
    RoleId.BARON: RoleDefinition(
        id=RoleId.BARON,
        type=CharacterType.MINION,
        name_zh="男爵",
        name_en="Baron",
        description_zh="在游戏准备阶段，增加两名外来者，减少两名镇民。",
        first_night_order=None,
        other_night_order=None,
    ),

    # ------------------ DEMONS (1) ------------------
    RoleId.IMP: RoleDefinition(
        id=RoleId.IMP,
        type=CharacterType.DEMON,
        name_zh="小恶魔",
        name_en="Imp",
        description_zh="每晚（除首夜外），选择一名玩家：他死亡。如果你因此自杀，一名存活的爪牙会成为小恶魔。",
        first_night_order=None,
        other_night_order=5,
    ),
}


def get_role(role_id: RoleId | str) -> RoleDefinition:
    if isinstance(role_id, str):
        role_id = RoleId(role_id)
    return ROLES[role_id]
